[package]
name = "base100"
version = "0.1.0"
authors = ["Adam Niederer <Adam.Niederer@gmail.com>"]
license = "AGPL-3.0"

[dependencies]
clap = {version = "2.19", features = ["yaml"]}
lazy_static = "0.2"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
panic = "abort"